SETTINGS:
  LEVEL: "VANILLA"
  #VANILLA - Vanilla level
  ABILITY: "&9Ability: &a#action# - #ability# - #delay#s"
ACTION:
  - RIGHT_CLICK
  - LEFT_CLICK
  - SHIFT_RIGHT_CLICK
  - SHIFT_LEFT_CLICK
CLICK_TYPE:
  RIGHT_CLICK: "Right Click"
  LEFT_CLICK: "Left Click"
  SHIFT_RIGHT_CLICK: "Shift Right Click"
  SHIFT_LEFT_CLICK: "Shift Left Click"
PREFIX: "&7[&eDItems&7]"